### ISSUE TITLE
Plugin isn't working

### ISSUE THREAD

**Issue by rodrigolitzius** [MindustryInside/jseval#4]
The 1.3 plugin isn't working, i enter the code, the console responds saying that it works, but it didn't.

Me: /js UnitTypes.beta.weapons.get(0).reload = 999
Console: 999

But on the game the reload is normal.

**Comment by King-BR** [comment]
I can confirm that no error shows up on the server side console

**Comment by rodrigolitzius** [comment]
And i respawned the unit too

**Comment by antsif-a** [comment]
The plugin works, these are mistakes on your side. Try `/sync`'ing with server.

**Comment by King-BR** [comment]
tried `/sync`'ing, rejoining the server and restarting the server. Nothing worked

**Comment by antsif-a** [comment]
Try running the `js` command with same code on the server console, if the result is the same, then this is not a plugin error.
