### ISSUE TITLE
How to disable promt?

### ISSUE THREAD

**Issue by isamuel-fs** [MindustryInside/jseval#7]
I have a few mods that narrate/simplify use of JS scripts with UI, but every time i use them, chat is filled with "unidentified". I might be a dummy but please help.

**Comment by nekonya3031** [comment]
as far as I know, this plugin is completely only for the server. As for "undefined", it's just the output of the value of the expression. Apparently the last of the methods has the void type.. @peXu-main

**Comment by isamuel-fs** [comment]
@misaka0954, yes, this is a mod, but hidden type, it is a client-side features that help me simplify use of JS with UIs: Modding Toolbox, Unit Factory ect.

**Comment by antsif-a** [comment]
Plugins are actually mods with "hidden" enabled by default. You shouldn't use them on client-side.
